import Vue from 'vue';
import PrimeVue from 'primevue/config';
import Card from 'primevue/card';
import InputText from 'primevue/inputtext';
import Button from 'primevue/button';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Password from 'primevue/password';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import Menubar from 'primevue/menubar';
import Sidebar from 'primevue/sidebar';
import TieredMenu from 'primevue/tieredmenu';
import Dialog from 'primevue/dialog';
import Avatar from 'primevue/avatar';
import AvatarGroup from 'primevue/avatargroup';
import FileUpload from 'primevue/fileupload';
import Calendar from 'primevue/calendar';
import Toolbar from "primevue/toolbar";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import Dropdown from 'primevue/dropdown';
import VuePapaParse from 'vue-papa-parse';
import Checkbox from 'primevue/checkbox';
Vue.use(VuePapaParse)
Vue.use(PrimeVue);
Vue.component('Button', Button);
Vue.component('Card', Card);
Vue.component('InputText', InputText);
Vue.component('TabView', TabView);
Vue.component('TabPanel', TabPanel);
Vue.component('Password', Password);
Vue.component('Toast', Toast);
Vue.component('Menubar', Menubar);
Vue.component('Sidebar', Sidebar);
Vue.component('TieredMenu', TieredMenu);
Vue.component('Dialog', Dialog);
Vue.component('Avatar', Avatar);
Vue.component('AvatarGroup', AvatarGroup);
Vue.component('FileUpload', FileUpload);
Vue.component('Calendar', Calendar);
Vue.component('Toolbar', Toolbar);
Vue.component('DataTable', DataTable);
Vue.component('Column', Column);
Vue.component('Dropdown', Dropdown);
Vue.component('Checkbox', Checkbox);
Vue.use(ToastService);